### PR TITLE
Made API http call and parsed JSON data into pojo

### PR DESCRIPTION
**Pull request by nurettn**
Issue #2 solved. 
Backend now works great. The code gets informations via API http call and parses into pojo. The JTable can be populated by this now.

### CODE REVIEW

**Comment by Freakston** [comment]
Hi @nurettinabaci Sorry fort the late reply. We are facing some issues running the file. Would you mind sharing the requirements for running this project. I am using java version "1.8.0_221" on vscode.

**Comment by Freakston** [comment]
Hi @nurettinabaci  I've gone through the code and there are a lot of problems I'm listing a few of the errors which I've encountered.

1. Setting the asteroidlist as private.Since it is private the line " window.asteroidList.setVisible(true);" at line 160 in panel1.java throws an error.
image

We can fix this by changing that to public.

2. The date format parser doesn't seem to be working.

I don't know if its because of not having the needed libraries. But it would be great if you could fix these. We could merge this PR if you want.

**Comment by nurettn** [comment]
Hi @Freakston I will fix that today, after that you can merge

**Comment by Freakston** [comment]
Hi @nurettinabaci it would be really great if we can discuss about this issue on our telegram group . I will be closing the PR because of the compilation errors and we had already assigned the task to a different person. If you are still interested in working on the issue you could talk about it on the telegram group. We might be able to merge some parts of your code.

https://t.me/AsteroidTracker

**Comment by Freakston** [comment]
@nurettinabaci If you are not on telegram you could mail me.

**Pull request closed without merging**
